### ISSUE TITLE
무슨 봇인가요

### ISSUE THREAD

**Issue by yangdoyun446** [sw08/Finix#1]
무슨 봇인지 설명해주시면 감사하겠습니다.

**Comment by sw08** [comment]
수학이랑 뭐 잡다한 것들이랑 뭐 그런 거 있는 잡봇이에요

**Comment by yangdoyun446** [comment]
그렇군요 만약 합격된다면 팀 채팅에서 봅시다

**Comment by sw08** [comment]
엌
팀빗 면접에서 오셨구나
이제알았네요
